/** Preact integration for `@casys/mcp-view-components` surfaces. */

export { definePreactComponent, preactSurfaceRenderer, startPreactSurfaceApp } from "./surface.ts";
export {
  ArtifactRow,
  Badge,
  Button,
  Card,
  CrossSelection,
  DataTable,
  ElementBody,
  ElementIdent,
  ElementProvenance,
  ElementReading,
  ElementVerdict,
  EmptyState,
  KeyValueList,
  LimitGauge,
  Message,
  Metric,
  MetricGrid,
  PathBar,
  SemanticElement,
  Stack,
  StateMessage,
  Toolbar,
} from "../../preact-components.ts";
export type {
  PreactComponentRenderer,
  PreactSurfaceAppOptions,
  PreactSurfaceAppState,
  PreactSurfaceComponentProps,
  PreactSurfaceContext,
  SurfaceMessageKind,
} from "./surface.ts";
export type {
  ArtifactFingerprint,
  ArtifactRowProps,
  ArtifactVerification,
  BadgeProps,
  ButtonProps,
  CardProps,
  CrossSelectionProps,
  DataTableColumn,
  DataTableProps,
  ElementBodyProps,
  ElementIdentProps,
  ElementProvenanceProps,
  ElementReadingProps,
  ElementVerdictProps,
  EmptyStateProps,
  KeyValueItem,
  KeyValueListProps,
  LimitGaugeLimit,
  LimitGaugeProps,
  MessageProps,
  MetricGridProps,
  MetricItem,
  MetricProps,
  PathBarItem,
  PathBarProps,
  PresentationTone,
  SemanticElementDensity,
  SemanticElementProps,
  StackProps,
  StateMessageProps,
  ToolbarProps,
} from "../../preact-components.ts";
